### ISSUE TITLE
program counter in RST function

### ISSUE THREAD

**Issue by companje** [dankar/altair8800#1]
Thanks for your great project!

There might be a bug on this line: https://github.com/dankar/altair8800/blob/master/src/intel8080.c#L931
I think the program counter should not be increased here because then it might return to the middle of an instruction.

**Comment by dankar** [comment]
Hm, are you sure? The purpose is to get a pointer to the next instruction, and since RST is 1 byte, I add 1. (CALL does pc+3 since a CALL is 3 bytes long)

**Comment by companje** [comment]
I think you're right. I had problems with it while implementing interrupts because when RST is called because of an interrupt the program counter should not increase since the RST is not part of the program. However when it is called by regular code it should increase the program counter like you implemented correctly.

**Comment by dankar** [comment]
Ah, got it. I haven't gotten to real interrupts, but maybe some day! Thanks for keeping an eye out.
